apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cusy25qqy-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cusy25qqy-go 
  name: cusy25qqy-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: cusy25qqy-go 
